# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: preact  ruby lib

Gem::Specification.new do |s|
  s.name = "preact"
  s.version = ""

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Christopher Gooley"]
  s.date = "2015-01-27"
  s.description = "API library to allow you to connect and submit customer actions to your Preact account"
  s.email = "gooley@preact.io"
  s.extra_rdoc_files = [
    "LICENSE.txt"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "Rakefile",
    "lib/generators/preact_generator.rb",
    "lib/preact.rb",
    "lib/preact/background_logger.rb",
    "lib/preact/client.rb",
    "lib/preact/configuration.rb",
    "lib/preact/objects/action_link.rb",
    "lib/preact/objects/api_object.rb",
    "lib/preact/objects/event.rb",
    "lib/preact/rails.rb",
    "lib/preact/rails/controllers/helpers.rb",
    "lib/preact/sidekiq.rb",
    "lib/preact/sidekiq/preact_logging_worker.rb",
    "lib/preact/version.rb",
    "lib/preact/warden.rb",
    "lib/preact/warden/hooks.rb",
    "preact.gemspec",
    "readme.md",
    "spec/preact_logging_worker_spec.rb",
    "spec/preact_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/lessneglect/lessneglect-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "LessNeglect client API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>, [">= 0"])
      s.add_runtime_dependency(%q<sucker_punch>, ["~> 1.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<multi_json>, [">= 0"])
      s.add_dependency(%q<sucker_punch>, ["~> 1.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<multi_json>, [">= 0"])
    s.add_dependency(%q<sucker_punch>, ["~> 1.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

